### PR TITLE
Update kernel version to v4.19.177-cip44

### PR DESCRIPTION
**Pull request by terasawa-lin**
# Purpose of pull request
Update kernel version to v4.19.177-cip44

### CODE REVIEW

**Comment by hiraku-wfs** [comment]
Which is correct?
- v4.19.177-cip44
- v4.19.177-cip47

**Comment by terasawa-lin** [comment]
I'm sorry. I made a mistake.
v4.19.177-cip44 is correct and has been fixed.

**Comment by hiraku-wfs** [comment]
> v4.19.177-cip44 is correct and has been fixed.

Got it. Thanks!

**Comment by hiraku-wfs** [comment]
Thanks!

**Pull request merged**
