### PR TITLE
Add PV to linux and linux-libc-headers recipes

### PR DESCRIPTION
**Pull request by masami256**
# Purpose of pull request

Current linux-libc-headers version uses Linux kernels's git revision. However, it makes problem that linux-libc-header and linux-libc-header-k510 uses same revision eventhough they use different revision. So set PV to specify package version.

# Test
## How to test

Check its version by bitbake-layers command.

```
bitbake-layers show-recipes | grep "linux-libc-headers" -A1
```

Build core-image-minimal and check correct version was built.

## Test result

DISTRO=emlinux

```
masami@ubuntu1804:~/emlinux/qemuarm64-emlinux$ grep ^DISTRO conf/local.conf 
DISTRO ?= "poky"
DISTRO = "emlinux"
masami@ubuntu1804:~/emlinux/qemuarm64-emlinux$ bitbake-layers show-recipes | grep "linux-libc-headers" -A1
linux-libc-headers:
  meta                 5.0
linux-libc-headers-base:
  meta-debian          4.19
linux-libc-headers-k510:
  meta-emlinux         5.10
masami@ubuntu1804:~/emlinux/qemuarm64-emlinux$ ls tmp-glibc/work/aarch64-emlinux-linux | grep linux-libc-headers
linux-libc-headers-base/
masami@ubuntu1804:~/emlinux/qemuarm64-emlinux$ ls tmp-glibc/work/aarch64-emlinux-linux/linux-libc-headers-base/
./  ../  4.19-r0/
```

DISTRO=emlinux-k510

```
masami@ubuntu1804:~/emlinux/qemuarm64-k510$ grep ^DISTRO conf/local.conf
DISTRO ?= "poky"
DISTRO = "emlinux-k510"
masami@ubuntu1804:~/emlinux/qemuarm64-k510$ bitbake-layers show-recipes | grep "linux-libc-headers" -A1
linux-libc-headers:
  meta                 5.0
linux-libc-headers-base:
  meta-debian          4.19
linux-libc-headers-k510:
  meta-emlinux         5.10
masami@ubuntu1804:~/emlinux/qemuarm64-k510$ ls tmp-glibc/work/aarch64-emlinux-linux | grep linux-libc-headers
linux-libc-headers-k510/
masami@ubuntu1804:~/emlinux/qemuarm64-k510$ ls tmp-glibc/work/aarch64-emlinux-linux/linux-libc-headers-k510/
./  ../  5.10-r0/
```

### CODE REVIEW

**Comment by hiraku-wfs** [comment]
It looks good for linux-libc-headers. Could you add PV for linux-{base,k510} as well?

**Comment by masami256** [comment]
> It looks good for linux-libc-headers. Could you add PV for linux-{base,k510} as well?

@hiraku-wfs Is it okay to set 4.19/5.10 to PV ? or do you prefer complete version like v4.19.207-cip-59?

**Comment by hiraku-wfs** [comment]
@masami256

> Is it okay to set 4.19/5.10 to PV ?

4.19/5.10 are okay currently.

**Comment by masami256** [comment]
> @masami256
> 
> > Is it okay to set 4.19/5.10 to PV ?
> 
> 4.19/5.10 are okay currently.

Added PV to kernel recipes too.

if DISTRO is emlinux,  linux-base version is 4.19.

```
linux-base:
  meta-debian          4.19
linux-dummy:
  meta                 unknown (skipped)
linux-firmware:
  meta                 1:20190815
linux-firmware-rpidistro:
  meta-emlinux         20190114-1+rpt10
linux-k510:
  meta-emlinux         git (skipped)
```

And, kernel image and module names contain its PV.

```
Image--4.19-r0-qemuarm64-20211013225849.bin
modules--4.19-r0-qemuarm64-20211013225849.tgz
```

emlinux-k510 is same as emlinux. 

```
linux-base:
  meta-debian          git (skipped)
linux-dummy:
  meta                 unknown (skipped)
linux-firmware:
  meta                 1:20190815
linux-firmware-rpidistro:
  meta-emlinux         20190114-1+rpt10
linux-k510:
  meta-emlinux         5.10
```

```
Image--5.10-r0-qemuarm64-20211013225855.bin
modules--5.10-r0-qemuarm64-20211013225855.tgz
```

**Comment by hiraku-wfs** [comment]
Thanks!

**Pull request merged**
