### PR TITLE
Support genericx86-64 machine type

### PR DESCRIPTION
**Pull request by masami256**
# Purpose of pull request

This PR support genericx86-64 machine.

# Test
## How to test

Add meta-yocto-bsp layer.
Set following lines in your local.conf then build core-image-minimal or core-image-weston.

```
MACHINE = "genericx86-64"
PREFERRED_PROVIDER_virtual/kernel = "linux-base"
``` 
## Test result

Build success.

### CODE REVIEW

**Comment by hiraku-wfs** [comment]
Could you remove grub and grub-efi from BBMASK in scripts/bbmask.conf, and add meta-yocto-bsp layer in scripts/setup-emlinux?

**Comment by masami256** [comment]
> Could you remove grub and grub-efi from BBMASK in scripts/bbmask.conf, and add meta-yocto-bsp layer in scripts/setup-emlinux?

sure.

**Comment by masami256** [comment]
@hiraku-wfs updated this pr.

core-image-weston is also supported.

weston

**Comment by hiraku-wfs** [comment]
Thanks!

**Pull request merged**
