### PR TITLE
Add support for qemu arm 32bit

### PR DESCRIPTION
**Pull request by kkobayas0**
This change adds a new machine support for qemu arm 32bit.

### CODE REVIEW

**Comment by masami256** [comment]
Do we need commit b278b6cf06fd549d7091941d23ef1ccf1ea9d1cf ?

**Comment by kkobayas0** [comment]
@masami256 
> Do we need commit [b278b6c](https://github.com/miraclelinux/meta-emlinux/commit/b278b6cf06fd549d7091941d23ef1ccf1ea9d1cf) ?

It just shows my old changes had no conflicts when the latest code was merged automatically with `git merge`. There is no effect on the code in the repository.

**Comment by masami256** [comment]
@kkobayas0 I merged it. 
btw, Please do not include unnecessary commit next time because we  don't need your local merge log.

**Comment by kkobayas0** [comment]
@masami256 
> @kkobayas0 I merged it. btw, Please do not include unnecessary commit next time because we don't need your local merge log.

I understood you don't like merge commits performed in each developer's machine. I will not include merge commits in my PR from now on.

The following is for your information. GitHub leaves a method for merging a PR to a committer. You can consider using the options described in the following document.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/merging-a-pull-request

For this case, I think `Squash and merge` or `Rebase and merge` can remove an unnecessary commit log for you when a PR is merged. Each method can be selected with one click operation.

In actual, GitHub projects are placed on the Internet, so it is impractical to restrict some git operations against all developers and they may suffer inconvenience caused by the lost utilities for that. Using such a option would be useful to make preferred commit logs without complication.

**Pull request merged**
